#!/bin/sh
### BEGIN INIT INFO
# Provides: btsyncd
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Should-Start: $network
# Should-Stop: $network
# Default-Start:
# Default-Stop: 0 1 6
# Short-Description: Multi-user daemonized version of btsync.
# Description: Starts the btsync daemon for all registered users.
### END INIT INFO

# Replace with linux users you want to run BTSync clients for
BTUSER="<EFFECTIVE_USER>"
CONFIG="<CONFIG_FILE>"
DAEMON=/usr/bin/btsync

#source /etc/rc.d/init.d/functions

#functions
RETVAL=0

start() {
    logger " Starting BTSync"
    if [ -f $config ]; then
      logger " Starting BTSync :: has config"
      sudo -b -u $BTUSER bash -c "$DAEMON --config $CONFIG"
      RETVAL=$?
    else
      logger " Starting BTSync :: does not has config. skipping"
      RETVAL=1
    fi
}


stop() {
    logger " Stoping BTSync"
    dbpid=`pgrep -fu $BTUSER $DAEMON`
    if [ ! -z "$dbpid" ]; then
      logger " Stoping BTSync :: pid $dbpid exists"
      killall btsync
      #daemon -o -c $BTUSER -K -u $BTUSER -x $DAEMON
      RETVAL=$?
    else
      logger " Stoping BTSync :: no pid"
      RETVAL=1
    fi
}

status() {
    logger " Checking BTSync"
    dbpid=`pgrep -fu $BTUSER $DAEMON`
    if [ -z "$dbpid" ]; then
      logger " Checking BTSync :: Not running"
    else
      logger " Checking BTSync :: running"
    fi
}


case "$1" in
 start)
  start
  ;;
 stop)
  stop
  ;;
 restart|reload|force-reload)
  stop
  start
  RETVAL=$?
  ;;
 status)
  status
  RETVAL=$?
  ;;
 *)
  echo "Usage: /etc/init.d/btsyncd {start|stop|reload|force-reload|restart|status}"
  exit 1
esac

exit $RETVAL

