## CREATE NEW USER ##
CREATE USER <WP USER NAME>@localhost IDENTIFIED BY "<WP PASSWORD>";

## CREATE NEW DATABASE ##
CREATE DATABASE <WP DB NAME>;

## GRANT needed permissions ##
GRANT ALL ON <WP DB NAME>.* TO <WP USER NAME>@localhost;

## FLUSH privileges ##
FLUSH PRIVILEGES;

## Exit ##
exit

